#!/usr/bin/env python3
"""Generate Cypher import scripts from extracted triples and entities.

Reads <output_dir>/triples.jsonl and entities.jsonl, writes (load in this order):
  cypher/00_constraints_neo4j.cypher    OR   00_constraints_memgraph.cypher  (pick your DB)
  cypher/01_entities.cypher    MERGE nodes, batched UNWIND per label
  cypher/02_relations.cypher   MERGE relationships, batched UNWIND per type

The 01/02 files are portable openCypher (load in Neo4j, Memgraph, FalkorDB); only the
constraint/index DDL in 00 is dialect-specific, hence one file per database.
This script never connects to a database — load the files yourself, e.g.:
  cypher-shell -u neo4j -p <pass> -f 00_constraints_neo4j.cypher

Python 3 stdlib only. No network, no subprocess.
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

DEFAULT_LABEL = "Entity"
DEFAULT_BATCH = 500


def cypher_str(value):
    """Render a Python string as a single-quoted Cypher string literal."""
    out = str(value)
    out = out.replace("\\", "\\\\").replace("'", "\\'")
    out = out.replace("\r", "\\r").replace("\n", "\\n").replace("\t", "\\t")
    return f"'{out}'"


def cypher_ident(name, fallback):
    """Render a node label / relationship type, backtick-quoted when needed."""
    name = str(name).strip() or fallback
    name = name.replace("`", "")  # backticks cannot be escaped inside backtick quoting
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        return name
    return f"`{name}`"


def read_jsonl(path):
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            yield json.loads(line)


def batched(items, size):
    for i in range(0, len(items), size):
        yield items[i:i + size]


def render_row(fields):
    return "{" + ", ".join(f"{k}: {v}" for k, v in fields) + "}"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("output_dir", help="extraction output directory")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH,
                        help=f"rows per UNWIND statement (default {DEFAULT_BATCH})")
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    triples = list(read_jsonl(out_dir / "triples.jsonl"))
    if not triples:
        print(f"error: no triples found in {out_dir / 'triples.jsonl'}", file=sys.stderr)
        return 1

    # Nodes: union of the entity registry and every triple endpoint, keyed by
    # name. The registry wins on type; aliases from repeated lines are merged.
    nodes = {}  # name -> {"type": str, "aliases": set}
    def add_node(name, etype, aliases=(), overwrite_type=False):
        node = nodes.setdefault(name, {"type": etype or DEFAULT_LABEL, "aliases": set()})
        if etype and (overwrite_type or node["type"] == DEFAULT_LABEL):
            node["type"] = etype
        node["aliases"].update(a for a in aliases if a and a != name)

    for triple in triples:
        add_node(triple["subject"], triple.get("subject_type"))
        add_node(triple["object"], triple.get("object_type"))
    for ent in read_jsonl(out_dir / "entities.jsonl"):
        add_node(ent["name"], ent.get("type"), ent.get("aliases") or [], overwrite_type=True)

    cypher_dir = out_dir / "cypher"
    cypher_dir.mkdir(exist_ok=True)

    header = ("// Generated by knowledge-graph-extract generate_cypher.py — plain Cypher, no parameters.\n"
              "// Load with: cypher-shell -f <file>   or paste into Neo4j Browser / Memgraph.\n")

    by_label = defaultdict(list)
    for name, node in sorted(nodes.items()):
        by_label[node["type"]].append((name, sorted(node["aliases"])))

    # --- 00_constraints_*.cypher: index the MERGE key (:Label {name}) so the loads
    # below are index lookups, not full label scans (seconds vs hours on a big graph).
    # Constraint/index DDL is the one place Neo4j and Memgraph syntax genuinely diverge
    # (the UNWIND/MERGE/MATCH in 01 and 02 are portable), so emit one file per dialect —
    # load the one that matches your database FIRST, then 01, then 02.
    labels = sorted(cypher_ident(label, DEFAULT_LABEL) for label in by_label)
    neo4j = ["// Generated by knowledge-graph-extract — Neo4j. Load FIRST, then 01, then 02.",
             "// A uniqueness constraint also creates the index that makes the MERGEs fast."]
    neo4j += [f"CREATE CONSTRAINT IF NOT EXISTS FOR (n:{ident}) REQUIRE n.name IS UNIQUE;"
              for ident in labels]
    (cypher_dir / "00_constraints_neo4j.cypher").write_text("\n".join(neo4j) + "\n", encoding="utf-8")

    memgraph = ["// Generated by knowledge-graph-extract — Memgraph. Load FIRST, then 01, then 02.",
                "// A label-property index makes the MERGE (n:Label {name}) lookups fast."]
    memgraph += [f"CREATE INDEX ON :{ident}(name);" for ident in labels]
    (cypher_dir / "00_constraints_memgraph.cypher").write_text("\n".join(memgraph) + "\n", encoding="utf-8")

    # --- 01_entities.cypher: group by label ---
    lines = [header]
    for label in sorted(by_label):
        ident = cypher_ident(label, DEFAULT_LABEL)
        lines.append(f"// {len(by_label[label])} nodes :{ident}")
        for batch in batched(by_label[label], args.batch_size):
            rows = ",\n  ".join(
                render_row([("name", cypher_str(name)),
                            ("aliases", "[" + ", ".join(cypher_str(a) for a in aliases) + "]")])
                for name, aliases in batch)
            lines.append(
                f"UNWIND [\n  {rows}\n] AS row\n"
                f"MERGE (n:{ident} {{name: row.name}})\n"
                f"SET n.aliases = row.aliases;\n")
    (cypher_dir / "01_entities.cypher").write_text("\n".join(lines), encoding="utf-8")

    # --- 02_relations.cypher: group by (relation, subject label, object label)
    # so MATCH clauses can use labels (relationship types and labels cannot be
    # parameterized or taken from row values in plain Cypher). Within a group,
    # collapse triples that share the same (subject, object) into one relationship
    # and collect every "doc#chunk" that asserted it, so provenance is lossless
    # (all sources kept, not just the last) and re-running is idempotent (each SET
    # rewrites the complete source list rather than appending duplicates).
    by_rel = defaultdict(dict)  # (rel, s_label, o_label) -> {(subject, object): set(sources)}
    for t in triples:
        s_label = nodes[t["subject"]]["type"]
        o_label = nodes[t["object"]]["type"]
        source = f"{t.get('doc', '')}#{t.get('chunk', '')}"
        pairs = by_rel[(t["relation"], s_label, o_label)]
        pairs.setdefault((t["subject"], t["object"]), set()).add(source)

    lines = [header]
    total_rels = 0
    for (rel, s_label, o_label), pairs in sorted(by_rel.items()):
        rel_ident = cypher_ident(rel, "RELATED_TO")
        s_ident = cypher_ident(s_label, DEFAULT_LABEL)
        o_ident = cypher_ident(o_label, DEFAULT_LABEL)
        lines.append(f"// {len(pairs)} rels (:{s_ident})-[:{rel_ident}]->(:{o_ident})")
        total_rels += len(pairs)
        for batch in batched(sorted(pairs.items()), args.batch_size):
            rows = ",\n  ".join(
                render_row([("s", cypher_str(s)),
                            ("o", cypher_str(o)),
                            ("sources", "[" + ", ".join(cypher_str(src) for src in sorted(srcs)) + "]")])
                for (s, o), srcs in batch)
            lines.append(
                f"UNWIND [\n  {rows}\n] AS row\n"
                f"MATCH (a:{s_ident} {{name: row.s}})\n"
                f"MATCH (b:{o_ident} {{name: row.o}})\n"
                f"MERGE (a)-[r:{rel_ident}]->(b)\n"
                f"SET r.sources = row.sources;\n")
    (cypher_dir / "02_relations.cypher").write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {cypher_dir}/00_constraints_neo4j.cypher and 00_constraints_memgraph.cypher "
          f"({len(by_label)} labels)")
    print(f"wrote {cypher_dir / '01_entities.cypher'} ({len(nodes)} nodes, {len(by_label)} labels)")
    print(f"wrote {cypher_dir / '02_relations.cypher'} ({total_rels} relationships, {len(by_rel)} groups)")
    print("load order: the 00_constraints file for your DB -> 01_entities.cypher -> 02_relations.cypher")
    return 0


if __name__ == "__main__":
    sys.exit(main())
