"""Partition the codex into a navigable tree, and assemble a chapter packet.

`Graph/nodes/codex_entry.jsonl` is the source of truth. Rendering it flat gave
one file of 602 entries — the whole corpus or nothing. This module renders the
navigation that makes retrieval programmatic instead:

* one file per entry at ``Codex/entries/<category>/<slug>.md``;
* a rendered ``README.md`` in every occupied partition, and a root index;
* a chapter window computed on demand from the ``triggers`` each entry
  already carries, never a stored field.

The rules live in ``Graph/schema.yaml`` — the categories, the partition path,
which categories are always on, and how the window is computed. Nothing here
invents a dimension: ``**Kategorie:**`` and ``triggers`` are already on the
records.

    from tools import kpcodex, kpgraph
    graph = kpgraph.load()
    files = kpcodex.all_views(graph)                  # path -> rendered text
    packet = kpcodex.packet(graph, 3, kpcodex.chapter_texts())

Standard library plus PyYAML, which the repo already uses for the wiki schema.
"""
from __future__ import annotations

import re
from functools import lru_cache
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SCHEMA_FILE = "Graph/schema.yaml"
CHAPTER_GLOB = "Manuscript/**/chapters/*.md"
SUMMARY_WORDS = 40
PREVIEW_CHARS = 500

# Bodies were ingested with paragraph breaks collapsed to runs of two or more
# spaces, so a "paragraph" splits on either.
PARA_SPLIT = re.compile(r"\n\s*\n|\s{2,}")
KATEGORIE = re.compile(r"\*\*Kategorie:\*\*\s*(.+)$")
QUELLE = re.compile(r"##\s*Quelle:\s*(\S+)")

HEADER = ("<!-- GENERATED by scripts/render_codex_views.py from Graph/ — "
          "do not edit by hand; change the record and re-render. -->\n\n")


@lru_cache(maxsize=1)
def schema(root: Path | str | None = None) -> dict:
    """The rules in ``Graph/schema.yaml``."""
    return yaml.safe_load((Path(root or ROOT) / SCHEMA_FILE).read_text(encoding="utf-8"))


def categories() -> list[str]:
    return list(schema()["categories"])


def always_on() -> set[str]:
    return set(schema()["always_on_categories"])


def codex_root() -> str:
    """Where entries live, repo-relative — `Codex/entries`."""
    return schema()["partition"]["codex_root"]


def codex_dir() -> str:
    """The rendered layer itself, repo-relative — `Codex`."""
    return codex_root().split("/", 1)[0]


# --- reading a body ------------------------------------------------------------------


def paragraphs(body: str) -> list[str]:
    return [p.strip() for p in PARA_SPLIT.split((body or "").strip()) if p.strip()]


def kategorie(body: str) -> str:
    """The `**Kategorie:**` first line, which is the real category."""
    for para in paragraphs(body)[:2]:
        found = KATEGORIE.match(para)
        if found:
            return found.group(1).strip()
    return ""


def quelle(body: str) -> str:
    for para in paragraphs(body)[:2]:
        found = QUELLE.match(para)
        if found:
            return found.group(1)
    return ""


def first_paragraph(body: str, limit: int = PREVIEW_CHARS) -> str:
    """The first paragraph that is neither the category line nor the source line."""
    for para in paragraphs(body):
        if para.startswith("**Kategorie:**") or para.startswith("## Quelle:"):
            continue
        return para if len(para) <= limit else para[: limit - 1] + "…"
    return ""


def summary(body: str, words: int = SUMMARY_WORDS) -> str:
    return " ".join(first_paragraph(body).split()[:words])


def partition_of(entry: dict) -> str:
    """The directory an entry belongs in; unknown categories are visibly misfiled."""
    found = (kategorie(entry.get("body", "")) or entry.get("kind", "")).strip().lower()
    return found if found in set(categories()) else schema()["partition"]["misfiled"]


def entry_path(entry: dict) -> str:
    return f"{codex_root()}/{partition_of(entry)}/{entry['slug']}.md"


# --- the chapter window --------------------------------------------------------------


def chapter_texts(root: Path | str | None = None) -> dict[int, str]:
    """Chapter number -> lower-cased prose, for the trigger scan."""
    directories = sorted(Path(root or ROOT).glob(CHAPTER_GLOB))
    texts = {}
    for path in directories:
        if path.name[:2].isdigit():
            texts.setdefault(int(path.name[:2]), path.read_text(encoding="utf-8").lower())
    return texts


def triggers_of(entry: dict) -> list[str]:
    floor = schema()["retrieval"]["window"]["min_trigger_length"]
    return [t.strip().lower() for t in (entry.get("triggers") or "").split(",")
            if len(t.strip()) >= floor]


def window_of(entry: dict, chapters: dict[int, str]) -> list[int]:
    """Chapters whose prose puts this entry in play — membership, not span."""
    triggers = triggers_of(entry)
    return sorted(n for n, text in chapters.items() if any(t in text for t in triggers))


# --- rendering -----------------------------------------------------------------------


def render_entry(entry: dict, window: list[int]) -> str:
    body = entry.get("body", "")
    lines = [HEADER, f"# {entry.get('name', entry['slug'])}\n",
             f"`{entry['slug']}` · {partition_of(entry)} · kind `{entry.get('kind', '')}`\n"]
    if window:
        lines.append(f"Chapters in play: {', '.join(str(n) for n in window)}\n")
    if entry.get("triggers"):
        lines.append(f"Triggers: {entry['triggers']}\n")
    source = quelle(body)
    if source:
        lines.append(f"Source: `{source}`\n")
    lines.append("## Eintrag\n")
    lines += [p for p in paragraphs(body)
              if not p.startswith("**Kategorie:**") and not p.startswith("## Quelle:")]
    lines.append("")
    lines.append(f"[Up]({'../README.md'})")
    return "\n".join(lines) + "\n"


def render_partition_index(category: str, entries: list[dict]) -> str:
    lines = [HEADER, f"# Codex — {category} ({len(entries)})\n", "[Up](../README.md)\n",
             "| entry | slug | chapters | summary |", "|---|---|---|---|"]
    for entry in entries:
        window = entry.get("_window") or []
        span = f"{window[0]}–{window[-1]}" if len(window) > 1 else (str(window[0]) if window else "—")
        lines.append(f"| [{entry.get('name', entry['slug'])}]({entry['slug']}.md) "
                     f"| `{entry['slug']}` | {span} | {summary(entry.get('body', ''))} |")
    return "\n".join(lines) + "\n"


def render_root_index(counts: dict[str, int]) -> str:
    total = sum(counts.values())
    lines = [HEADER, f"# Codex entries ({total})\n", "[Up](../GLOSSARY.md)\n",
             "One file per entry, partitioned by the `**Kategorie:**` each record carries",
             "(`Graph/schema.yaml`). Assemble a chapter packet with",
             "`python3 scripts/context_packet.py --chapter N` rather than reading a whole",
             "partition.\n",
             "| partition | entries | always on |", "|---|---:|---|"]
    for category in categories() + [schema()["partition"]["misfiled"]]:
        count = counts.get(category, 0)
        if count == 0 and category == schema()["partition"]["misfiled"]:
            continue
        mark = "yes" if category in always_on() else ""
        lines.append(f"| [{category}]({category}/README.md) | {count} | {mark} |")
    return "\n".join(lines) + "\n"


def entries_folder() -> str:
    """The entries directory, relative to the rendered layer — `entries`."""
    return codex_root().split("/", 1)[1]


def entry_views(graph, chapters: dict[int, str] | None = None) -> dict[str, str]:
    """The entry tree and its indexes, keyed by repo-relative path."""
    chapters = chapters if chapters is not None else chapter_texts()
    folder = codex_root()
    grouped: dict[str, list[dict]] = {}
    files: dict[str, str] = {}
    for entry in sorted(graph.nodes("CodexEntry"), key=lambda e: e["slug"]):
        window = window_of(entry, chapters)
        entry = {**entry, "_window": window}
        grouped.setdefault(partition_of(entry), []).append(entry)
        files[f"{folder}/{partition_of(entry)}/{entry['slug']}.md"] = render_entry(entry, window)
    for category, group in grouped.items():
        files[f"{folder}/{category}/README.md"] = render_partition_index(category, group)
    counts = {k: len(v) for k, v in grouped.items()}
    files[f"{folder}/README.md"] = render_root_index(counts)
    files[f"{codex_dir()}/GLOSSARY.md"] = _glossary_router(counts)
    return files


def _glossary_router(counts: dict[str, int]) -> str:
    """The root glossary: counts and links, never an entry body."""
    from .views import render_router

    folder = entries_folder()
    rows = [(category, f"{folder}/{category}/README.md", counts.get(category, 0))
            for category in categories() + [schema()["partition"]["misfiled"]]
            if counts.get(category, 0) or category in categories()]
    return render_router(
        "Glossar — Kohärenz Protokoll",
        "Die Begriffe, Regeln, Motive, Stimmen und Orte des Romans, partitioniert nach "
        "der `**Kategorie:**`, die jeder Datensatz bereits trägt. Normativ bleibt "
        "`Canon/` — bei Konflikt gewinnt "
        "`kohaerenz-protokoll_storyform-und-outline_2026-06-10.md`.",
        rows, folder)


def all_views(graph, chapters: dict[int, str] | None = None) -> dict[str, str]:
    """Every file the rendered layer owns, keyed by repo-relative path."""
    from .views import axiom_views, timeline_views

    files = entry_views(graph, chapters)
    files.update(axiom_views(graph))
    files.update(timeline_views(graph))
    return files


# --- the packet ----------------------------------------------------------------------


def packet(graph, chapter: int, chapters: dict[int, str] | None = None) -> dict:
    """The tiers `Graph/schema.yaml` declares, for one chapter."""
    chapters = chapters if chapters is not None else chapter_texts()
    on = always_on()
    always, anchored = [], []
    for entry in sorted(graph.nodes("CodexEntry"), key=lambda e: e["slug"]):
        if partition_of(entry) in on:
            always.append(entry)
        elif chapter in window_of(entry, chapters):
            anchored.append(entry)
    return {"chapter": chapter, "always_on": always, "anchored": anchored,
            "axioms": graph.nodes("WorldAxiom")}
