#!/usr/bin/env python3
"""Fills the two generated tables of `Plan/concept/graph-contracts_2026-09-30.md` — the catalogue of the 32 contracts and the
precision of the labelled rows — between their `<!--CATALOGUE-->` and `<!--PRECISION-->` markers, from what is on disk.

The catalogue reads every staged run (`hegraph.staged()`), so a contract's *documents* and *rows* are the files' counts; the
precision reads `Plan/runs/hyperextract-templates-2026-09-30/labels.jsonl` (`hegraph.labels()`), so it is only as many rows as
a reader has labelled, and says how many. Nothing is edited by hand between the markers. Run from any directory:

    python3 Plan/runs/hyperextract-templates-2026-09-30/fill_concept.py

It was a scratch file until 2026-09-30, when the backfill made the tables change a second time; it is kept so that they can be
regenerated by anyone. Standard library plus `scripts/hegraph.py`.
"""
import os
from pathlib import Path
ROOT = Path(__file__).resolve().parents[3]
os.chdir(ROOT)
import json, math, sys
from collections import Counter, defaultdict
sys.path.insert(0, str(ROOT / "scripts"))
import hegraph

FAMILY = {
 "terms": ["TermReadings", "TermDefinitions", "TermContrasts", "AliasPairs", "Analogies", "TermTaxonomy", "StatedRelations", "RelationReadings", "TermCensus", "LocationRegistry"],
 "claims and sources": ["CausalLinks", "Rules", "Quantities", "Attributions", "StandingClaims", "OpenPoints", "Locks"],
 "plot and chapters": ["ChapterCards", "ChapterBeats", "StructureBeats", "Storypoints", "Precedence", "Anchors", "ThemeMotifs", "Pitch"],
 "cast and voice": ["CastRoles", "CardFields", "EntityFacts", "Knowledge", "ProseRules", "DiegeticTerms", "Utterances"],
}
FROM = {
 "TermReadings": "the notes: what a document says about a term, with its line (#124)",
 "TermDefinitions": "„what is X“ is best answered by the sentence that defines X; `TermReadings` ranks a definition no higher than a remark",
 "TermContrasts": "the author's reading of „Große Stille“ against „das große Schweigen“ as a tension, found by a BM25 relation",
 "AliasPairs": "diagnosis: 9 of 96 gold pages have no seed because the question names a page under a name no page carries",
 "Analogies": "the census's `lens` sections: a fictional term and the real concept the document says it corresponds to",
 "TermTaxonomy": "diagnosis: `[[links]]` are untyped, so a class and its member cannot be told apart",
 "StatedRelations": "#124's comparison of graph tools: nodes and edges a document states",
 "RelationReadings": "`StatedRelations` that keeps hedges and questions",
 "TermCensus": "the reader's candidate lists",
 "LocationRegistry": "document 6's master table of places",
 "CausalLinks": "the plot model as checkable rules; „why does X happen“ has no stated relation",
 "Rules": "GOAL: the plot model as checkable rules; the §5.4 rule table",
 "Quantities": "the number 734 and the 39 or 40 chapters: a number is no term",
 "Attributions": "the reader lab: voice was the defect no check saw — what a line reports, not what the document says",
 "StandingClaims": "GOAL: sources tiered by precedence; what a document says of its own standing",
 "OpenPoints": "GOAL: self-generated questions; what a document itself leaves open",
 "Locks": "GOAL §4.2 claim schema `lock`; the C11 case",
 "ChapterCards": "plan Phase 2b: one treatment paragraph per movement — who, want, obstacle, hooks",
 "ChapterBeats": "decision 013: the chapter is a unit; 98 chapter mentions have no reading yet",
 "StructureBeats": "developmental-editor's structure criteria; GOAL §5.1",
 "Storypoints": "GOAL §4.3 `Storypoint`, `Throughline`, the dual storyform",
 "Precedence": "no ordering relation in the stated graph",
 "Anchors": "plan Phase 2c anchors ledger; GOAL §4.3 `Anchor`, `ForeshadowStrand`",
 "ThemeMotifs": "developmental-editor's spine; workshop-critique's reading of what a piece is about",
 "Pitch": "developmental intake; agent-first-pages",
 "CastRoles": "character pages and storyform documents assign figures to roles",
 "CardFields": "character-card-builder, reverse-character-cards; the plan's cast ledger",
 "EntityFacts": "continuity-editor's style sheet",
 "Knowledge": "the plan's reader-knowledge ledger; GOAL §4.3 `ReaderKnowledgeState`",
 "ProseRules": "the plan's rulebook (Phase 2d); GOAL §5.4",
 "DiegeticTerms": "GOAL §4.3 `DiegeticTerm`: theory shows as image, space or behaviour",
 "Utterances": "dialogue-gym voice drills; the character card's voice field",
}

def wilson(k, n, z=1.645):
    if not n: return (0, 0)
    p = k / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    r = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return (max(0, (c - r) / d), min(1, (c + r) / d))

marked = hegraph.labels()
stat = defaultdict(lambda: {"docs": set(), "names": 0, "quote": 0, "lab": Counter()})
for slug, run, row in hegraph.staged():
    name = row["template"].removesuffix(".yaml")
    s = stat[name]; s["docs"].add(slug); s[row["admitted"]] += 1
    m = marked.get(row["id"][6:14])
    if m:
        s["lab"][m["label"]] += 1
        if m.get("sample") == "scaled documents": s.setdefault("lab2", Counter())[m["label"]] += 1
import glob
tried = defaultdict(set); empty = Counter()
for f in glob.glob("Plan/runs/*/hyperextract/*/usage.json"):
    u = json.load(open(f)); n = u["template"].removesuffix(".yaml"); tried[n].add(f.split("/")[2])
    if str(u.get("failed", "")).startswith("empty or invalid candidate list") and not u.get("failed_calls"): empty[n] += 1

out = ["| family | contract | relation | derived from | documents | rows: names / quote | labelled | ok / ok+part |", "|---|---|---|---|---|---|---|---|"]
for fam, names in FAMILY.items():
    for n in names:
        s = stat.get(n); d = len(tried.get(n, ())) or (len(s["docs"]) if s else 0)
        lab = s["lab"] if s else Counter(); nl = sum(lab.values())
        rows = f"{s['names']} / {s['quote']}" if s and (s["names"] or s["quote"]) else ("found nothing" if empty[n] else "not run")
        pr = f"{lab['ok'] / nl:.0%} / {(lab['ok'] + lab['part']) / nl:.0%}" if nl else ""
        out.append(f"| {fam} | `{n}` | `P_HE_{hegraph.KIND[n]}` | {FROM[n]} | {d} | {rows} | {nl or ''} | {pr} |")
        fam = ""
catalogue = "\n".join(out)

prec = ["| contract | labelled | ok | part | wrong | ok share, 90 % interval | ok + part | on the scaled documents: labelled, ok |", "|---|---|---|---|---|---|---|---|"]
rows = []
for n, s in stat.items():
    lab = s["lab"]; nl = sum(lab.values())
    if nl: rows.append((lab["ok"] / nl, n, lab, nl))
for share, n, lab, nl in sorted(rows, key=lambda r: (-r[0], -r[3])):
    lo, hi = wilson(lab["ok"], nl)
    l2 = stat[n].get("lab2", Counter()); n2 = sum(l2.values())
    sc = f"{n2}, {l2['ok'] / n2:.0%}" if n2 else ""
    prec.append(f"| `{n}` | {nl} | {lab['ok']} | {lab['part']} | {lab['wrong']} | {share:.0%} [{lo:.0%}, {hi:.0%}] | {(lab['ok'] + lab['part']) / nl:.0%} | {sc} |")
precision = "\n".join(prec)

import re
P = "Plan/concept/graph-contracts_2026-09-30.md"
t = open(P, encoding="utf-8").read()
def put(t, tag, body):
    start, end = f"<!--{tag}-->", f"<!--/{tag}-->"
    if end in t:
        return re.sub(re.escape(start) + r".*?" + re.escape(end), lambda m: start + "\n" + body + "\n" + end, t, flags=re.S)
    assert start in t, tag
    return t.replace(start, start + "\n" + body + "\n" + end)
t = put(t, "CATALOGUE", catalogue)
t = put(t, "PRECISION", precision)
open(P, "w", encoding="utf-8").write(t)
print("filled", len(catalogue), len(precision))
