#!/usr/bin/env python3
"""Render the Codex/ wiki views from the provenance graph (read-only).

The Worldbuilding-Codex suite (`.claude/skills/*`, `/lint-wiki`, `/query`)
expects a GLOSSARY, a MASTER-TIMELINE and an index of world rules. In this
repo those facts already live in `.agency/session.db` as CodexEntry,
StoryTimeEvent, WorldAxiom and World nodes (seeded from Canon/ by
`scripts/ingest_canon.py`). Rather than keeping a second, hand-edited copy
that drifts, this script renders derived Markdown views from graph ground
truth — the same relationship `materialize_manuscript.py` has to chapters.

    python3 scripts/render_codex_views.py            # write Codex/*.md
    python3 scripts/render_codex_views.py --check    # exit 1 if views are stale
    python3 scripts/render_codex_views.py --stdout   # print, don't write

Never hand-edit the generated files: change the graph through capability
verbs (create_codex_entry, update_codex_entry, record_story_event,
create_world_axiom) and re-render. Only live node versions are rendered
(bi-temporal `vto` still open); archived codex entries are skipped.
"""
from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / ".agency" / "session.db"
OUT = ROOT / "Codex"
OPEN_VTO = 1_000_000_000_000
NOVEL = "novel:9d170c31"

HEADER = (
    "<!-- GENERATED by scripts/render_codex_views.py from .agency/session.db — "
    "do not edit by hand; change the graph and re-render. -->\n\n"
)

# Story-time phases in narrative order; `when_story` is free text, so each
# event is bucketed by the first phase whose pattern matches.
PHASES = [
    ("Genesis — vor der Romanhandlung", r"^Genesis(?!-Krise)|Basisrealität|atemporal"),
    ("Genesis-Krise / Trennung", r"Genesis-Krise|^Krise|Fragmentierung|Ende der Genesis"),
    ("Romanbeginn / Akt I", r"Romanbeginn|Akt I(?![I-])|früher Akt I"),
    ("Akt II", r"Akt II(?!I)|Beginn Akt II|Ende Akt II"),
    ("Akt III-A (vor Vortex 1)", r"Akt III"),
    ("Vortex 1", r"^Vortex 1"),
    ("Nach Vortex 1 — trügerischer Frieden", r"nach Vortex 1"),
    ("Vortex 2", r"^Vortex 2"),
]


def connect() -> sqlite3.Connection:
    return sqlite3.connect(f"file:{DB}?mode=ro", uri=True)


def nodes(c: sqlite3.Connection, label: str) -> list[dict]:
    """All live nodes of `label` with their text/int/bool props merged."""
    out = []
    for (nid,) in c.execute(
            "SELECT node_id FROM node_labels WHERE label=?", (label,)):
        props: dict = {"_nid": nid}
        for table, cast in (("node_props_text", str), ("node_props_int", int),
                            ("node_props_bool", bool)):
            for k, v in c.execute(
                    f"SELECT pk.key, t.value FROM {table} t "
                    f"JOIN property_keys pk ON pk.id=t.key_id WHERE t.node_id=?",
                    (nid,)):
                props[k] = cast(v)
        if props.get("vto", OPEN_VTO) != OPEN_VTO:
            continue  # superseded revision
        out.append(props)
    return out


def edges(c: sqlite3.Connection, etype: str) -> list[tuple[int, int]]:
    return list(c.execute(
        "SELECT source_id, target_id FROM edges WHERE type=?", (etype,)))


# Codex bodies were ingested with paragraph breaks collapsed to runs of two
# or more spaces (no newlines survive), so "paragraphs" are split on either.
PARA_SPLIT = re.compile(r"\n\s*\n|\s{2,}")


def _paras(body: str) -> list[str]:
    return [p.strip() for p in PARA_SPLIT.split((body or "").strip()) if p.strip()]


def _kategorie(body: str) -> str | None:
    for p in _paras(body)[:2]:
        m = re.match(r"\*\*Kategorie:\*\*\s*(.+)$", p)
        if m:
            return m.group(1).strip()
    return None


def _source(body: str) -> str | None:
    for p in _paras(body)[:2]:
        m = re.match(r"## Quelle:\s*(\S+)", p)
        if m:
            return m.group(1)
    return None


def _first_para(body: str, limit: int = 500) -> str:
    for p in _paras(body):
        if p.startswith("**Kategorie:**") or p.startswith("## Quelle:"):
            continue
        return p if len(p) <= limit else p[: limit - 1] + "…"
    return ""


def render_glossary(c: sqlite3.Connection) -> str:
    entries = [e for e in nodes(c, "CodexEntry")
               if e.get("novel", NOVEL) == NOVEL and not e.get("archived")]
    by_group: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        kat = _kategorie(e.get("body", ""))
        group = f"{e.get('kind', '?')} · {kat}" if kat else e.get("kind", "?")
        by_group[group].append(e)

    lines = [HEADER, "# Glossar — Kohärenz Protokoll (generiert)\n",
             f"{len(entries)} CodexEntries aus dem Provenienz-Graphen, gruppiert nach "
             "`kind` (Codex-Enum) und `**Kategorie:**` (Original-Kategorie aus der "
             "Canon-Extraktion, siehe CLAUDE.md §3 Codex-Disziplin).\n",
             "Die vollständigen Einträge liegen im Graphen (`list_codex_entries`, "
             "`match_codex_entries`); hier steht pro Eintrag Name, Slug, Trigger und "
             "der erste Absatz. Normativ bleibt `Canon/` — bei Konflikt gewinnt "
             "`kohaerenz-protokoll_storyform-und-outline_2026-06-10.md`.\n",
             "## Inhalt\n"]
    for group in sorted(by_group):
        anchor = re.sub(r"[^a-z0-9]+", "-", group.lower()).strip("-")
        lines.append(f"- [{group}](#{anchor}) ({len(by_group[group])})")
    lines.append("")
    for group in sorted(by_group):
        lines.append(f"## {group}\n")
        for e in sorted(by_group[group], key=lambda x: x.get("name", "").lower()):
            trig = e.get("triggers", "").strip()
            src = _source(e.get("body", ""))
            lines.append(f"### {e.get('name', '?')}  `{e.get('slug', '')}`\n")
            meta = [f"id `{e.get('id', '')}`"]
            if src:
                meta.append(f"Quelle `{src}`")
            if trig:
                meta.append(f"Trigger: {trig}")
            lines.append("_" + " · ".join(meta) + "_\n")
            para = _first_para(e.get("body", ""))
            if para:
                lines.append(para + "\n")
    return "\n".join(lines)


def _phase_index(when: str) -> int:
    for i, (_, pat) in enumerate(PHASES):
        if re.search(pat, when or ""):
            return i
    return len(PHASES)


def render_timeline(c: sqlite3.Connection) -> str:
    events = [e for e in nodes(c, "StoryTimeEvent") if e.get("novel", NOVEL) == NOVEL]
    scenes = {s["_nid"]: s for s in nodes(c, "Scene")}
    chapters = {ch["_nid"]: ch for ch in nodes(c, "Chapter")}
    chapter_by_id = {ch.get("id"): ch for ch in chapters.values()}
    happens = defaultdict(list)   # event nid -> [scene]
    reveals = defaultdict(list)
    for s, t in edges(c, "HAPPENS_AT"):
        if t in scenes:
            happens[s].append(scenes[t])
        elif s in scenes:
            happens[t].append(scenes[s])
    for s, t in edges(c, "REVEALED_IN"):
        if t in scenes:
            reveals[s].append(scenes[t])
        elif s in scenes:
            reveals[t].append(scenes[s])

    def scene_ref(sc: dict) -> str:
        ch = chapter_by_id.get(sc.get("chapter"), {})
        num = ch.get("number")
        return f"Kap {num} / {sc.get('slug', '')}" if num is not None else sc.get("slug", "")

    buckets: dict[int, list[dict]] = defaultdict(list)
    for e in events:
        buckets[_phase_index(e.get("when_story", ""))].append(e)

    lines = [HEADER, "# Master-Timeline — Kohärenz Protokoll (generiert)\n",
             f"{len(events)} StoryTimeEvents aus dem Graphen, nach Story-Zeit gebucht. "
             "`when_story` ist Freitext; die Phasen-Zuordnung ist eine Lesehilfe, "
             "kein Kanon. Erzählreihenfolge der Beats: `narrative_order`.\n"]
    for i, (title, _) in enumerate(PHASES + [("Nicht zugeordnet", "")]):
        evs = buckets.get(i, [])
        if not evs:
            continue
        lines.append(f"## {title}\n")
        lines.append("| Story-Zeit | Ereignis | passiert in | enthüllt in |")
        lines.append("|---|---|---|---|")
        for e in sorted(evs, key=lambda x: (x.get("when_story", ""), x.get("label", ""))):
            h = ", ".join(scene_ref(s) for s in happens.get(e["_nid"], [])) or "—"
            r = ", ".join(scene_ref(s) for s in reveals.get(e["_nid"], [])) or "—"
            lines.append(f"| {e.get('when_story', '')} | {e.get('label', '')} | {h} | {r} |")
        lines.append("")
    return "\n".join(lines)


def render_axioms(c: sqlite3.Connection) -> str:
    worlds = {w["_nid"]: w for w in nodes(c, "World")}
    axioms = {a["_nid"]: a for a in nodes(c, "WorldAxiom")}
    of_world: dict[int, list[dict]] = defaultdict(list)
    placed = set()
    for s, t in edges(c, "PART_OF_WORLD"):
        if s in axioms and t in worlds:
            of_world[t].append(axioms[s]); placed.add(s)
        elif t in axioms and s in worlds:
            of_world[s].append(axioms[t]); placed.add(t)
    lines = [HEADER, "# Welt-Axiome — Kohärenz Protokoll (generiert)\n",
             f"{len(axioms)} WorldAxioms in {len(worlds)} Welten. Schwere: `hard` = "
             "Verstoß ist ein Defekt; `soft` = Reviewer prüft. Quelle der Wahrheit: "
             "`Canon/kohaerenz-protokoll_kernwelten-vollstaendig_2026-06-10.md` und "
             "`…_welt-sensorik-drafting_2026-06-10.md`; Widersprüche meldet "
             "`find_axiom_contradictions(world_id)`.\n"]
    for w in sorted(worlds.values(), key=lambda x: x.get("name", "")):
        axs = of_world.get(w["_nid"], [])
        lines.append(f"## {w.get('name', '?')}  `{w.get('id', '')}`\n")
        if not axs:
            lines.append("_keine Axiome erfasst_\n")
            continue
        for a in sorted(axs, key=lambda x: (x.get("severity", ""), x.get("text", ""))):
            lines.append(f"- **[{a.get('severity', '?')}]** {a.get('text', '')}")
        lines.append("")
    orphans = [a for nid, a in axioms.items() if nid not in placed]
    if orphans:
        lines.append("## Ohne Welt-Zuordnung\n")
        for a in orphans:
            lines.append(f"- **[{a.get('severity', '?')}]** {a.get('text', '')}")
        lines.append("")
    return "\n".join(lines)


VIEWS = {
    "GLOSSARY.md": render_glossary,
    "MASTER-TIMELINE.md": render_timeline,
    "WORLD-AXIOMS.md": render_axioms,
}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if Codex/ is stale")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    ns = ap.parse_args(argv)
    if not DB.is_file():
        print(f"no graph at {DB}", file=sys.stderr)
        return 2
    c = connect()
    stale = []
    for name, fn in VIEWS.items():
        content = fn(c)
        path = OUT / name
        if ns.stdout:
            print(content)
            continue
        if ns.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
            continue
        OUT.mkdir(exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)} ({len(content.splitlines())} lines)")
    c.close()
    if ns.check:
        if stale:
            print("STALE: " + ", ".join(stale) + " — run scripts/render_codex_views.py")
            return 1
        print("Codex/ views are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
