#!/usr/bin/env python3
"""Render the Codex/ wiki views from the provenance graph (read-only).

The Worldbuilding-Codex suite (`.claude/skills/*`, `/lint-wiki`, `/query`)
expects a GLOSSARY, a MASTER-TIMELINE and an index of world rules. In this
repo those facts already live in `.agency/session.db` as CodexEntry,
StoryTimeEvent, WorldAxiom and World nodes (seeded from Canon/ by
`scripts/ingest_canon.py`). Rather than keeping a second, hand-edited copy
that drifts, this script renders derived Markdown views from graph ground
truth — the same relationship `materialize_manuscript.py` has to chapters.

    python3 scripts/render_codex_views.py            # write Codex indexes + subpages
    python3 scripts/render_codex_views.py --check    # exit 1 if views are stale
    python3 scripts/render_codex_views.py --stdout   # print, don't write

Never hand-edit the generated files: change the graph through capability
verbs (create_codex_entry, update_codex_entry, record_story_event,
create_world_axiom) and re-render. Only live node versions are rendered
(bi-temporal `vto` still open); archived codex entries are skipped.
"""
from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / ".agency" / "session.db"
OUT = ROOT / "Codex"
OPEN_VTO = 1_000_000_000_000
NOVEL = "novel:9d170c31"

HEADER = (
    "<!-- GENERATED by scripts/render_codex_views.py from .agency/session.db — "
    "do not edit by hand; change the graph and re-render. -->\n\n"
)

# Story-time phases in narrative order; `when_story` is free text, so each
# event is bucketed by the first phase whose pattern matches.
PHASES = [
    ("Genesis — vor der Romanhandlung", r"^Genesis(?!-Krise)|Basisrealität|atemporal"),
    ("Genesis-Krise / Trennung", r"Genesis-Krise|^Krise|Fragmentierung|Ende der Genesis"),
    ("Romanbeginn / Akt I", r"Romanbeginn|Akt I(?![I-])|früher Akt I"),
    ("Akt II", r"Akt II(?!I)|Beginn Akt II|Ende Akt II"),
    ("Akt III-A (vor Vortex 1)", r"Akt III"),
    ("Vortex 1", r"^Vortex 1"),
    ("Nach Vortex 1 — trügerischer Frieden", r"nach Vortex 1"),
    ("Vortex 2", r"^Vortex 2"),
]


def connect() -> sqlite3.Connection:
    return sqlite3.connect(f"file:{DB}?mode=ro", uri=True)


def nodes(c: sqlite3.Connection, label: str) -> list[dict]:
    """All live nodes of `label` with their text/int/bool props merged."""
    out = []
    for (nid,) in c.execute(
            "SELECT node_id FROM node_labels WHERE label=?", (label,)):
        props: dict = {"_nid": nid}
        for table, cast in (("node_props_text", str), ("node_props_int", int),
                            ("node_props_bool", bool)):
            for k, v in c.execute(
                    f"SELECT pk.key, t.value FROM {table} t "
                    f"JOIN property_keys pk ON pk.id=t.key_id WHERE t.node_id=?",
                    (nid,)):
                props[k] = cast(v)
        if props.get("vto", OPEN_VTO) != OPEN_VTO:
            continue  # superseded revision
        out.append(props)
    return out


def edges(c: sqlite3.Connection, etype: str) -> list[tuple[int, int]]:
    return list(c.execute(
        "SELECT source_id, target_id FROM edges WHERE type=?", (etype,)))


# Codex bodies were ingested with paragraph breaks collapsed to runs of two
# or more spaces (no newlines survive), so "paragraphs" are split on either.
PARA_SPLIT = re.compile(r"\n\s*\n|\s{2,}")


def _paras(body: str) -> list[str]:
    return [p.strip() for p in PARA_SPLIT.split((body or "").strip()) if p.strip()]


def _kategorie(body: str) -> str | None:
    for p in _paras(body)[:2]:
        m = re.match(r"\*\*Kategorie:\*\*\s*(.+)$", p)
        if m:
            return m.group(1).strip()
    return None


def _source(body: str) -> str | None:
    for p in _paras(body)[:2]:
        m = re.match(r"## Quelle:\s*(\S+)", p)
        if m:
            return m.group(1)
    return None


def _first_para(body: str, limit: int = 500) -> str:
    for p in _paras(body):
        if p.startswith("**Kategorie:**") or p.startswith("## Quelle:"):
            continue
        return p if len(p) <= limit else p[: limit - 1] + "…"
    return ""


def _anchor(text: str) -> str:
    folded = text.lower().translate(str.maketrans({"ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"}))
    return re.sub(r"[^a-z0-9]+", "-", folded).strip("-")


def glossary_groups(c: sqlite3.Connection) -> dict[str, list[dict]]:
    entries = [e for e in nodes(c, "CodexEntry")
               if e.get("novel", NOVEL) == NOVEL and not e.get("archived")]
    by_group: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_group[e.get("kind", "unknown")].append(e)
    return by_group


def render_glossary(c: sqlite3.Connection) -> str:
    by_group = glossary_groups(c)
    total = sum(len(entries) for entries in by_group.values())
    lines = [HEADER, "# Glossar — Kompatibilitätsindex (generiert)\n",
             "[Codex-Übersicht](README.md) · [Glossar-Navigation](glossary/README.md)\n",
             f"{total} CodexEntries aus dem Provenienz-Graphen. Einträge liegen als "
             "kleine, einzeln ladbare Seiten unter `glossary/<kind>/<slug>.md`. "
             "Dieser historische Root-Pfad bleibt als kompatibler Einstieg erhalten; "
             "er enthält bewusst keine vollständigen Einträge.\n",
             "Für Kontextsuche: `python3 scripts/wiki_fts.py search \"<begriffe>\" "
             "--scope codex --limit 5`.\n", "## Arten\n"]
    for kind in sorted(by_group):
        lines.append(f"- [{kind}](glossary/{kind}/README.md) ({len(by_group[kind])})")
    return "\n".join(lines) + "\n"


def render_glossary_hub(c: sqlite3.Connection) -> str:
    by_group = glossary_groups(c)
    lines = [HEADER, "# Glossar\n", "[Codex](../README.md) · [Kompatibilitätsindex](../GLOSSARY.md)\n",
             "Wähle zuerst die Art oder nutze die Heading-Suche; lade nicht alle "
             "Eintragsseiten in den Arbeitskontext.\n"]
    for kind in sorted(by_group):
        lines.append(f"- [{kind}]({kind}/README.md) — {len(by_group[kind])} Einträge")
    return "\n".join(lines) + "\n"


def render_glossary_kind(kind: str, entries: list[dict]) -> str:
    lines = [HEADER, f"# Glossar: {kind}\n", "[Glossar](../README.md) · [Codex](../../README.md)\n",
             "Kompakter Namensindex. Öffne nur die benötigte Eintragsseite.\n"]
    for e in sorted(entries, key=lambda item: item.get("name", "").lower()):
        trigger = e.get("triggers", "").strip()
        suffix = f" — {trigger}" if trigger else ""
        lines.append(f"- [{e.get('name', '?')}]({e.get('slug', '')}.md) "
                     f"`{e.get('slug', '')}`{suffix}")
    return "\n".join(lines) + "\n"


def render_glossary_entry(entry: dict) -> str:
    body = entry.get("body", "")
    category = _kategorie(body)
    source = _source(body)
    lines = [HEADER, f"# {entry.get('name', '?')}\n", "[Art-Index](README.md) · [Glossar](../README.md)\n",
             f"- **Slug:** `{entry.get('slug', '')}`",
             f"- **Graph-ID:** `{entry.get('id', '')}`",
             f"- **Art:** `{entry.get('kind', '')}`"]
    if category:
        lines.append(f"- **Kategorie:** `{category}`")
    if source:
        lines.append(f"- **Quelle:** `{source}`")
    if entry.get("triggers", "").strip():
        lines.append(f"- **Trigger:** {entry['triggers'].strip()}")
    lines.append("\n## Inhalt\n")
    content = [p for p in _paras(body)
               if not p.startswith("**Kategorie:**") and not p.startswith("## Quelle:")]
    lines.extend(content or ["_Kein gerenderter Inhalt._"])
    lines.extend(["\n## Kontextgrenze\n",
                  "Kapitel- und Spoilersicherheit ist für diesen Graph-Eintrag noch nicht "
                  "modelliert. Nicht ungeprüft in kapitelbegrenzten Kontext laden."])
    return "\n\n".join(lines) + "\n"

def _phase_index(when: str) -> int:
    for i, (_, pat) in enumerate(PHASES):
        if re.search(pat, when or ""):
            return i
    return len(PHASES)


def timeline_sections(c: sqlite3.Connection) -> tuple[int, list[tuple[str, list[list[str]]]]]:
    events = [e for e in nodes(c, "StoryTimeEvent") if e.get("novel", NOVEL) == NOVEL]
    scenes = {s["_nid"]: s for s in nodes(c, "Scene")}
    chapters = {ch["_nid"]: ch for ch in nodes(c, "Chapter")}
    chapter_by_id = {ch.get("id"): ch for ch in chapters.values()}
    happens = defaultdict(list)   # event nid -> [scene]
    reveals = defaultdict(list)
    for s, t in edges(c, "HAPPENS_AT"):
        if t in scenes:
            happens[s].append(scenes[t])
        elif s in scenes:
            happens[t].append(scenes[s])
    for s, t in edges(c, "REVEALED_IN"):
        if t in scenes:
            reveals[s].append(scenes[t])
        elif s in scenes:
            reveals[t].append(scenes[s])

    def scene_ref(sc: dict) -> str:
        ch = chapter_by_id.get(sc.get("chapter"), {})
        num = ch.get("number")
        return f"Kap {num} / {sc.get('slug', '')}" if num is not None else sc.get("slug", "")

    buckets: dict[int, list[dict]] = defaultdict(list)
    for e in events:
        buckets[_phase_index(e.get("when_story", ""))].append(e)

    sections = []
    for i, (title, _) in enumerate(PHASES + [("Nicht zugeordnet", "")]):
        evs = buckets.get(i, [])
        if not evs:
            continue
        rows = []
        for e in sorted(evs, key=lambda x: (x.get("when_story", ""), x.get("label", ""))):
            h = ", ".join(scene_ref(s) for s in happens.get(e["_nid"], [])) or "—"
            r = ", ".join(scene_ref(s) for s in reveals.get(e["_nid"], [])) or "—"
            rows.append([e.get("when_story", ""), e.get("label", ""), h, r])
        sections.append((title, rows))
    return len(events), sections


def render_timeline(c: sqlite3.Connection) -> str:
    total, sections = timeline_sections(c)
    lines = [HEADER, "# Master-Timeline — Kompatibilitätsindex (generiert)\n",
             "[Codex-Übersicht](README.md) · [Timeline-Navigation](timeline/README.md)\n",
             f"{total} StoryTimeEvents, auf kleine Phasenansichten verteilt. "
             "Dieser Root-Pfad bleibt als kompatibler Index erhalten.\n", "## Phasen\n"]
    for title, rows in sections:
        lines.append(f"- [{title}](timeline/{_anchor(title)}.md) ({len(rows)})")
    return "\n".join(lines) + "\n"


def render_timeline_hub(c: sqlite3.Connection) -> str:
    total, sections = timeline_sections(c)
    lines = [HEADER, "# Timeline\n", "[Codex](../README.md) · [Kompatibilitätsindex](../MASTER-TIMELINE.md)\n",
             f"{total} StoryTimeEvents. `when_story` ist Freitext; die "
             "Phasen-Zuordnung ist eine Lesehilfe, kein Kanon.\n"]
    for title, rows in sections:
        lines.append(f"- [{title}]({_anchor(title)}.md) — {len(rows)} Ereignisse")
    return "\n".join(lines) + "\n"


def render_timeline_phase(title: str, rows: list[list[str]]) -> str:
    lines = [HEADER, f"# {title}\n", "[Timeline](README.md) · [Codex](../README.md)\n",
             "| Story-Zeit | Ereignis | passiert in | enthüllt in |",
             "|---|---|---|---|"]
    lines.extend("| " + " | ".join(str(cell).replace("|", "\\|") for cell in row) + " |"
                 for row in rows)
    return "\n".join(lines) + "\n"


def world_sections(c: sqlite3.Connection) -> tuple[int, list[tuple[dict, list[dict]]], list[dict]]:
    worlds = {w["_nid"]: w for w in nodes(c, "World")}
    axioms = {a["_nid"]: a for a in nodes(c, "WorldAxiom")}
    of_world: dict[int, list[dict]] = defaultdict(list)
    placed = set()
    for s, t in edges(c, "PART_OF_WORLD"):
        if s in axioms and t in worlds:
            of_world[t].append(axioms[s]); placed.add(s)
        elif t in axioms and s in worlds:
            of_world[s].append(axioms[t]); placed.add(t)
    orphans = [a for nid, a in axioms.items() if nid not in placed]
    sections = [(world, of_world.get(world["_nid"], []))
                for world in sorted(worlds.values(), key=lambda x: x.get("name", ""))]
    return len(axioms), sections, orphans


def render_axioms(c: sqlite3.Connection) -> str:
    total, sections, orphans = world_sections(c)
    lines = [HEADER, "# Welt-Axiome — Kompatibilitätsindex (generiert)\n",
             "[Codex-Übersicht](README.md) · [Welten-Navigation](worlds/README.md)\n",
             f"{total} WorldAxioms in {len(sections)} Welten, verteilt auf kleine "
             "Weltansichten. Dieser Root-Pfad bleibt als kompatibler Index erhalten.\n",
             "## Welten\n"]
    for world, axioms in sections:
        slug = world.get("slug") or _anchor(world.get("name", "unknown"))
        lines.append(f"- [{world.get('name', '?')}](worlds/{slug}.md) ({len(axioms)})")
    if orphans:
        lines.append(f"- [Ohne Welt-Zuordnung](worlds/ohne-welt-zuordnung.md) ({len(orphans)})")
    return "\n".join(lines) + "\n"


def render_worlds_hub(c: sqlite3.Connection) -> str:
    total, sections, orphans = world_sections(c)
    lines = [HEADER, "# Welten und Axiome\n", "[Codex](../README.md) · [Kompatibilitätsindex](../WORLD-AXIOMS.md)\n",
             f"{total} WorldAxioms. `hard` bezeichnet einen Defekt bei Verstoß; "
             "`soft` verlangt eine Prüfung.\n"]
    for world, axioms in sections:
        slug = world.get("slug") or _anchor(world.get("name", "unknown"))
        lines.append(f"- [{world.get('name', '?')}]({slug}.md) — {len(axioms)} Axiome")
    if orphans:
        lines.append(f"- [Ohne Welt-Zuordnung](ohne-welt-zuordnung.md) — {len(orphans)} Axiome")
    return "\n".join(lines) + "\n"


def render_world_page(title: str, world_id: str, axioms: list[dict]) -> str:
    lines = [HEADER, f"# {title}\n", "[Welten](README.md) · [Codex](../README.md)\n"]
    if world_id:
        lines.append(f"**Graph-ID:** `{world_id}`\n")
    if not axioms:
        lines.append("_Keine Axiome erfasst._")
    else:
        for axiom in sorted(axioms, key=lambda item: (item.get("severity", ""), item.get("text", ""))):
            lines.append(f"- **[{axiom.get('severity', '?')}]** {axiom.get('text', '')}")
    return "\n".join(lines) + "\n"


def render_readme(c: sqlite3.Connection) -> str:
    groups = glossary_groups(c)
    entries = sum(len(items) for items in groups.values())
    events, _ = timeline_sections(c)
    axioms, worlds, _ = world_sections(c)
    return "\n".join([
        HEADER,
        "# Codex — generierte Graphansichten\n",
        "Der Codex ist eine kompakte, vollständig generierte Projektion aus "
        "`.agency/session.db`; normativ bleibt `Canon/`. Nie von Hand editieren.\n",
        "## Navigation\n",
        f"- [Glossar](glossary/README.md) — {entries} einzeln ladbare Einträge",
        f"- [Timeline](timeline/README.md) — {events} Ereignisse nach Phase",
        f"- [Welten und Axiome](worlds/README.md) — {axioms} Axiome in {len(worlds)} Welten",
        "- [Kontextgrenzen](context/README.md) — bekannte Retrieval-Grenzen und Datenlücken\n",
        "## Kontext-effizient arbeiten\n",
        "1. `python3 scripts/wiki_fts.py build`",
        "2. Für Kapitelarbeit: `python3 scripts/codex_context.py \"<begriffe>\" --chapter N`",
        "   Für ausdrücklich whole-novel Arbeit: `python3 scripts/codex_context.py \"<begriffe>\" --whole-novel`.",
        "3. Nur die zurückgegebenen Dateien und Zeilenbereiche öffnen.",
        "4. Für kapitelbegrenzte Arbeit zuerst `Wiki/context-map.md` anwenden; "
        "CodexEntries besitzen derzeit noch keine verlässliche Spoilergrenze.\n",
        "Historische Root-Dateien bleiben als kleine Kompatibilitätsindizes bestehen. "
        "Die Detailseiten werden mit `python3 scripts/render_codex_views.py` aktualisiert.",
    ]) + "\n"


def render_context_limits(c: sqlite3.Connection) -> str:
    groups = glossary_groups(c)
    entries = sum(len(items) for items in groups.values())
    events, _ = timeline_sections(c)
    axioms, _, _ = world_sections(c)
    return "\n".join([
        HEADER,
        "# Kontextgrenzen\n",
        "[Codex](../README.md)\n",
        "Der Renderer erfindet keine Kapitel- oder Spoilermetadaten. Fehlende "
        "Felder sind eine sichtbare Datenlücke und keine Freigabe.\n",
        "| Entität | Anzahl | Kapitel-/Spoilergrenze | Sicherer Standard |",
        "|---|---:|---|---|",
        f"| CodexEntry | {entries} | nicht modelliert | nur nach Wiki-Routing und Prüfung laden |",
        f"| StoryTimeEvent | {events} | teilweise über REVEALED_IN ableitbar | Phasenansicht prüfen |",
        f"| WorldAxiom | {axioms} | nicht modelliert | als whole-novel-Regel behandeln |\n",
        "Benötigte künftige Graphfelder: `true_from`, `true_until`, "
        "`introduced_in`, `revealed_in` und `writer_safe_from`. Ihre Semantik wird "
        "vor einer Graphmigration separat beschlossen.",
    ]) + "\n"


GENERATED_DIRS = ("glossary", "timeline", "worlds", "context")


def render_files(c: sqlite3.Connection) -> dict[str, str]:
    rendered = {
        "README.md": render_readme(c),
        "GLOSSARY.md": render_glossary(c),
        "MASTER-TIMELINE.md": render_timeline(c),
        "WORLD-AXIOMS.md": render_axioms(c),
        "glossary/README.md": render_glossary_hub(c),
        "timeline/README.md": render_timeline_hub(c),
        "worlds/README.md": render_worlds_hub(c),
        "context/README.md": render_context_limits(c),
    }
    for kind, entries in glossary_groups(c).items():
        rendered[f"glossary/{kind}/README.md"] = render_glossary_kind(kind, entries)
        for entry in entries:
            slug = entry.get("slug", "")
            if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug):
                raise ValueError(f"invalid CodexEntry slug: {slug!r}")
            path = f"glossary/{kind}/{slug}.md"
            if path in rendered:
                raise ValueError(f"duplicate rendered path: {path}")
            rendered[path] = render_glossary_entry(entry)
    _, phases = timeline_sections(c)
    for title, rows in phases:
        rendered[f"timeline/{_anchor(title)}.md"] = render_timeline_phase(title, rows)
    _, worlds, orphans = world_sections(c)
    for world, axioms in worlds:
        slug = world.get("slug") or _anchor(world.get("name", "unknown"))
        rendered[f"worlds/{slug}.md"] = render_world_page(
            world.get("name", "?"), world.get("id", ""), axioms)
    if orphans:
        rendered["worlds/ohne-welt-zuordnung.md"] = render_world_page(
            "Ohne Welt-Zuordnung", "", orphans)
    return rendered


def stale_generated_files(expected: set[str]) -> list[Path]:
    stale = []
    for directory in GENERATED_DIRS:
        base = OUT / directory
        if not base.is_dir():
            continue
        stale.extend(path for path in base.rglob("*.md")
                     if path.relative_to(OUT).as_posix() not in expected)
    return sorted(stale)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if Codex/ is stale")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    ns = ap.parse_args(argv)
    if not DB.is_file():
        print(f"no graph at {DB}", file=sys.stderr)
        return 2
    c = connect()
    rendered = render_files(c)
    c.close()
    stale = []
    for name, content in sorted(rendered.items()):
        path = OUT / name
        if ns.stdout:
            print(f"<!-- {name} -->")
            print(content)
            continue
        if ns.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)} ({len(content.splitlines())} lines)")
    unexpected = stale_generated_files(set(rendered))
    if ns.check:
        stale.extend(path.relative_to(OUT).as_posix() for path in unexpected)
    elif not ns.stdout:
        for path in unexpected:
            path.unlink()
            print(f"removed stale generated view {path.relative_to(ROOT)}")
    if ns.check:
        if stale:
            print("STALE: " + ", ".join(sorted(stale)) + " — run scripts/render_codex_views.py")
            return 1
        print("Codex/ views are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
